### ISSUE TITLE
include more examples

### ISSUE THREAD

**Issue by nichtich** [nichtich/Pandoc-Elements#3]
Port all examples from https://github.com/jgm/pandocfilters/tree/master/examples to Perl

**Comment by nichtich** [comment]
Missing examples so far:

- [ ] abc.py (related to #12)
- [ ] gabc.py (related to #12)
- [ ] graphviz.py (related to #12)
- [ ] lilypond.py (related to #12)
- [ ] metavars.py (related to #10) 
- [ ] myemph.py (easy)
- [ ] theorem.py (easy)
- [ ] tikz.py (related to #12)

**Comment by nichtich** [comment]
See also <http://toolchain.gitbook.com/templating/> and <https://plugins.gitbook.com/>, for instance <https://plugins.gitbook.com/plugin/katex>

**Comment by nichtich** [comment]
For image generation also http://projects.haskell.org/diagrams/

**Comment by nichtich** [comment]
[As John MacFarlane stated](https://groups.google.com/d/msg/pandoc-discuss/wbebx65e1Nk/prx8_jLnAQAJ) panflute should be preferred, so better use [its filter examples](https://github.com/sergiocorreia/panflute/tree/master/examples/pandocfilters) as reference.
